### ISSUE TITLE
Problem with docker images

### ISSUE THREAD

**Issue by margmz** [mcabranches/bgp_ethereum#6]
Very interesting project. Do you have the docker images you use?

docker/R4# ./build.sh 
Sending build context to Docker daemon   5.12kB
Step 1/3 : FROM quaggabase:1
pull access denied for quaggabase, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by mcabranches** [comment]
Hi,

Please, first build the image on docker/quagga/.

**Comment by margmz** [comment]
Thanks!!!
